___

# Machine Learning in Geosciences ] 
Department of Applied Geoinformatics and Carthography, Charles University

Lukas Brodsky lukas.brodsky@natur.cuni.cz


### PyTorch installation

`pip install torch`
`pip install torchvision`

In [ ]:
# Successfully installed torch-1.11.0 torchvision-0.12.0

PyTorch includes a package called torchvision which is used to load and prepare the dataset. It includes two basic functions namely Dataset and DataLoader which helps in transformation and loading of dataset.

# PyTorch tensor

Tensors are the building blocks for representing data in PyThorch. It is the fundamental data structure. The term `tensor` comes bundled with the notion of spaces. In this context of deep learning, tensors refer to the generalization of vectors and matrices to an arbitrary number of dimensions. 

The torch package contains not only the data structures for **multi-dimensional arrays** but also defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

### PyTorch tensor vs. NumPy array

A PyTorch tensor is similar to a NumPy array (*lingua franca* of data science). However, PyTorch tensors usually utilize GPUs to accelerate their numeric computations. These tensors which are created in PyTorch can be used to fit a network. The user can manually implement the forward and backward passes through the network.

Note: PyTorch tensors vs. TensorFlow; 

The major difference between PyTorch and Tensor Flow’s is in the computational graphs. Tensor Flow uses static and PyTorch uses dynamic computational graphs. This makes difference in debuging the graphs. 

### Dynamic Graphs
Static graphs are nice because user can optimize the graph up front. If programmers are re-using the same graph over and over, then this potentially costly up-front optimization can be maintained as the same graph is rerun over and over.

The major difference between them is that Tensor Flow’s computational graphs are static and PyTorch uses dynamic computational graphs.

### The tensor API

The PyTorch API establish a few directions on where to find things in the documentation (https://pytorch.org/docs/stable/index.html). 

## Tensors: Multidimensional arrays

In [1]:
import torch 
import numpy as np

### PyTorch Tensors constructors 
Comparing NumPy and PyTorch

In [2]:
a = np.ones(3)
print(a)

[1. 1. 1.]


### Use torch.ones()

In [3]:
# constructing a one-dimensional tensor of size with ones
b = torch.ones(3)
print(b)

tensor([1., 1., 1.])


In [4]:
# slice
a[1]

1.0

#### Casting e.g. to float()

In [7]:
pass

#### Overvrite value in existing tensor

In [8]:
# overwrite third element with 2.0 in the tensor 
b[2] = 2.0
print(b)

tensor([1., 1., 2.])


#### Constructors from other containers

`torch.tensor()`

In [9]:
# passing Python list to te constructor, the same effect! 
l = [4.0, 1.0, 5.0, 3.0, 2.0, 1.0]
torch.tensor(l)

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
# 2D, (list of lists) passed to the constructor
l2d = [[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]
l2d_tensor = torch.tensor(l2d)
l2d_tensor

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

#### Dimensionality 
`tensor.shape`

In [13]:
l2d_tensor.shape

torch.Size([3, 2])

### Indexing tensors 

#### Slicing [:]

In [17]:
l2d_tensor[:,:]

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
# jen první sloupec, protože za dvojtečkou to bere do n, ne včetně, takže je potřeba psát n+1
l2d_tensor[:,0:1]

tensor([[4.],
        [5.],
        [2.]])

In [15]:
# Python list
some_list = list(range(5))

In [ ]:
# [:]
pass 

In [ ]:
# [1:3]
pass

In [ ]:
# [-1]
pass 

Tensors uses the same notion. We can use range indexing for each of the tensor's dimensions. 

In [ ]:
# tensor two indices to access 2D elements
# [0, 1]
pass 

In [ ]:
# the first row [0]
pass 

### Tensors storage

Values in tensors are allocated in **contignuous chunks of memory** managed by `torch.Storage` instances. A storage is a one-dimensional array of numerical data: that is, a contignuous block of memory containing numbers of a given type, such as float (32 bits representing floating-point number). A PyTorch `Tensor` instance is a view of such a `Storage` instance that is capable of indexing into that storage using an offset. Multiple tensors can index the same storage even if they index into the data differently. 


Each element is a 32-bit (4-byte) float (in the above case). Storing a 1D tensor of 1.000.000 float numbers will require 4.000.000 contignuous bytes plus small overhead for the metadata.  

#### `.storage()`

In [19]:
# indexing into the storage 
l2d = [[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]
points = torch.tensor(l2d)
# use method storage() to see the content
points.storage()

C:\Users\uzivatel\AppData\Local\Temp\ipykernel_14420\2044676178.py:5: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [20]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
# even though the tensor is 3x2, the storage is contignous array of size 6

In [21]:
# manual indexing into the storage
points_storage = points.storage()
# print points storage at [0]
points_storage[0]

4.0

In [22]:
points.storage()[1]

1.0

In [23]:
# changing the values in a storage leads to change in the tensor 
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In order to index into a storage, tensors rely on a few pieces of information that, toogether with their storage, unequivocally define them: **size**, **offset**, and **stride**. The size (or shape in NumPy world) is a tuple indicating how many elements across each dimension the tensor represents. The storage offset is the index in the storage corresponding to the first elemment in the tensor. The stride is the number of elements in the storage that need to be skipped over to obtain the next element along each dimension. 

In [24]:
# .size()
points.size()

torch.Size([3, 2])

In [25]:
# .storage_offset()
points.storage_offset()

0

In [26]:
# it is the same information contained in the .shape
points.shape

torch.Size([3, 2])

In [27]:
# stride: number of elements in the storage that have to be skipped 
# when the index is increased by 1 in each dimension
# .stride()
points.stride()

(2, 1)

### Transposing without copying

In [ ]:
# Let's take the point tensor where individual points in the rows and X and Y coordinates in the columns, 
# and turn it around so that points are in the columns. 

In [28]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [30]:
# use .t() function (transpose)
points_t = points.t()

In [32]:
# check the storage of the 'two' tensors with id 
id(points.storage()) == id(points_t.storage())

# mělo by to být false ale

True

### Specifying the numeric type with dtype 

The `dtype`argument to tensor constructors specifies the numerical data (d) type, similar to NumPy. 

* `torch.float` .. 32-bit floating point number

* `torch.double` .. 64-bit

* `torch.float16` or `torch.half` .. 16-bit

* `torch.int8` .. signed 8-bit integers

* `torch.uint8` .. unsigned 8-bit 

* `torch.int16` or `torch.short` .. signed 16-bit 

* `torch.int32` or `torch.int` .. signed 32-bit 

* `torch.int64` or `torch.long` .. signed 64-bit 

* `torch.bool` .. Boolean

Computations happening in neural networks are typically executed with 32-bit floating-point precision (`torch.float` or `torch.float32`).

Tensors can be used as indexes in other tensors, PyTorch expects indexing tensors to have 64-bit integer data type (`torch.int64`). 

Predicates on tensors, such as points > 1.0, produce `bool` tensors (`torch.bool`). 

### Managing a tensor's dtype attribute

In [34]:
# float: use dtype=torch.double in  torch.ones() constructor 
a = torch.ones(3, dtype=torch.double)
a

tensor([1., 1., 1.], dtype=torch.float64)

In [35]:
# integer: use dtype=torch.short torch.tensor() constructor 
b = torch.ones(3, dtype=torch.short)
b

tensor([1, 1, 1], dtype=torch.int16)

In [36]:
# check the tensor type .dtype
b.dtype

torch.int16

In [37]:
a.dtype 

torch.float64

In [38]:
# casting to .double()
b.double()
b


tensor([1, 1, 1], dtype=torch.int16)

In [40]:
# casting to .short()
a.short()
a

# tohle úplně nefunguje

tensor([1., 1., 1.], dtype=torch.float64)

In [41]:
# or the more convenient and readble method .to()
# tensor.to(torch.double)
b.to(torch.double)

tensor([1., 1., 1.], dtype=torch.float64)

In [42]:
# tensor.to(dtype=torch.short)
a.to(dtype=torch.short)

tensor([1, 1, 1], dtype=torch.int16)

In [ ]:
# mixing input data types in operations converts to the 'larger' type 
# multiply torch.double by torch.short
pass 

### Random values

In [50]:
# NumPy random 
np.random.seed(42)
x = np.random.rand(2,2)
x


array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [48]:
# Torch .rand() 
torch.manual_seed(42)
torch.rand(2,2) 

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [51]:
torch.tensor(x)

tensor([[0.3745, 0.9507],
        [0.7320, 0.5987]], dtype=torch.float64)

### Math operations


In [57]:
# Element wise addition
# c = a + b
a = torch.rand(1)
print(a)
b = torch.rand(1)
print(b)
c = a + b 
print(c)

tensor([0.2566])
tensor([0.7936])
tensor([1.0502])


In [58]:
# torch.add(a, b)
torch.add(a, b) 

tensor([1.0502])

In [59]:
# In-place addition, změním hodnotu a
# c.add_(a)
a.add_(b) 


tensor([1.0502])

In [60]:
# Multiplication, not in-place
# torch.mul(a, b)
torch.mul(a, b) 

tensor([0.8335])

In [67]:
# Tensor Mean
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
# tensor.mean(dim=0)

a.mean(dim=0) 
#torch.mean(a, dim=0)

tensor(5.)

Vast majority of operations on tensors are available in the `torch` module and can be called as methods of a tensor object. 

Look in to the web documentation(https://pytorch.org/docs/stable/index.html) for: 

* Math operations:     
    * Pointwise ops: 
    * Reduction ops: 
    * Comparision ops: 
    * Spectral ops: 


* Random sampling 

* Parallelism 

### PyTorch  Abstraction

`Tensor`: Like array in Numpy, but **runs on GPU** 

**`Variable`**: Stores data and **gradient**; Node in a computational graph; 


### PyTorch Variables
Variables allows us to accumulate gradients!

When using autograd, the forward pass of your network will define a computational graph; nodes in the graph will be Tensors, and edges will be functions that produce output Tensors from input Tensors.
PyTorch Tensors can be created as variable objects where a variable represents a node in computational graph.

In [68]:
from torch.autograd import Variable

a = Variable(torch.ones(2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [69]:
# not a variable
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

### What is requires_grad?
**Allows calculation of gradients w.r.t. the variable!**

### NumPy interoperability

PyTorch tensors can be converted to `NumPy`arrays and vice versa very efficiently. This allows to take advantage of huge swath of functionality in the wider Python ecosystem that has built up around the NumPy array type. The zero-copy interoperabilty with NumPy arrays is due to the storage system working with the Python buffer protocol (https://docs.python.org/3/c-api/buffer.html). 

In [72]:
# COnvert pytoch tensor to NumPy array 
points = torch.ones(3, 4)
#Use tensor.numpy()
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
# the returned array shares the same underlaying buffer with the tensor storage 

In [73]:
# type(points_np)
type(points_np)

numpy.ndarray

We can use such conversions at basically no cost, as long as the data sits in CPU RAM. However, if the tensor is allocated on the GPU, PyTorch will make a copy of the tensor into a NumPy array allocated on the CPU. 

In [74]:
# From NumPy to torch Tensor 
# .from_numpy(points_np)
torch.from_numpy(points_np)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [75]:
torch.tensor(points_np)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Serializing tensors

PyTorch uses `pickle` under the hood to serialize the tensor object, plus dedicated serialization code for the storage. 

In [76]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
# save our points tensor to a file
# torch.save(tensor, './ourtensor.t') → ikonka s velbloudem, ha ha
torch.save(points, './ourtensor.t')

In [ ]:
# we can pass a file descriptor in lieu of the file name
# with open('./ourpoints2.t','wb') as f:
#    torch.save(points, f)


In [79]:
# Use torch.load('pathfilename.t') to open and read the data
torch.load('./ourtensor.t') 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [80]:
# Correct error 
with open('./ourpoints.t','rb') as f:
   points = torch.load()

FileNotFoundError: [Errno 2] No such file or directory: './ourpoints.t'

### Moving tensors to the GPU

Every PyTorch tensor can be transferred to the GPU(s) in order to perform massively parrallel, fast computatios. In adition to `dtype`, a PyTorch `Tensor` also has the notion of `device`, which is where the computer the tensor data is placed. 

In [81]:
torch.cuda.is_available()

c:\Users\uzivatel\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


False

In [82]:
if torch.cuda.is_available(): 
    points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
else: 
    print('CUDA is not available')

CUDA is not available


We can also use the `to` method. 

In [ ]:
if torch.cuda.is_available(): 
    points_gpu = points.to(device='cuda')
else: 
    print('CUDA is not available')

The CPU- and GPU-based tensors expose the same user-facing API, making it much easier to write code that is agnostic to where, exactly, the heavy number crunching is running. 

In [ ]:
# specify the number of the GPU device 
if torch.cuda.is_available(): 
    points_gpu = points.to(device='cuda:0')
else: 
    print('CUDA is not available')

In [ ]:
# Some more GPU operations, if CUDA is installed 

In [ ]:
if torch.cuda.is_available(): 
    points = 2 * points  # <1> on CPU
    points_gpu = 2 * points.to(device='cuda')  # <2> on GPU 
else: 
    print('CUDA is not available')


In [ ]:
if torch.cuda.is_available(): 
    points_gpu = points_gpu + 4

In [ ]:
if torch.cuda.is_available(): 
    points_cpu = points_gpu.to(device='cpu')

We can also use the shorthand method `cpu`and `cuda` instead of the `to` method. 

In [ ]:
# points_gpu = points.cuda()  # <1>
# points_gpu = points.cuda(0)
# points_cpu = points_gpu.cpu() 